#ifndef ERROR_CODES_H
#define ERROR_CODES_H

typedef enum {
    FCP_OK,
    FCP_BAD_ARGUMENTS,
    FCP_BAD_FILE_SIZE,
    FCP_DIR_NOT_EXIST,
    FCP_SYSCALL_FAILED,
    FCP_UINT32_PARSE_FAILED,
    FCP_BAD_FILE_TYPE,
    FCP_POINTER_NULL,
    FCP_THREAD_CREATION_FAILED
} FCP_ERROR;

#endif

